ALTER TABLE public.reservations
  ADD COLUMN IF NOT EXISTS workshop_id TEXT,
  ADD COLUMN IF NOT EXISTS workshop_name TEXT,
  ADD COLUMN IF NOT EXISTS workshop_date TEXT,
  ADD COLUMN IF NOT EXISTS consent_reservation BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS consent_image BOOLEAN DEFAULT FALSE;
